name: CI - Build and Smoke Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm Install

      - name: Run app in background
        run: |
          node app.js &
          sleep 3

      - name: Run smoke test
        run: npm test

      - name: Build Docker image
        run: docker build -t devops2-app .